
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mustafayigitguzel
 */
public class StokUygulaması extends javax.swing.JFrame {

    /**
     * Creates new form StokUygulaması
     */
    public StokUygulaması() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_ürün_ismi = new javax.swing.JTextField();
        tf_fiyat = new javax.swing.JTextField();
        CBKategori = new javax.swing.JComboBox<>();
        MesajYazısı = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ÜrünTablosu = new javax.swing.JTable();
        Ürün_ekle = new javax.swing.JButton();
        ürün_güncelleme = new javax.swing.JButton();
        sil_butonu = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ürün ismi:");

        jLabel2.setText("Kategori: ");

        jLabel3.setText("Fiyat:");

        CBKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kültür Sanat", "Yemek", "Elektronik" }));

        MesajYazısı.setForeground(new java.awt.Color(255, 0, 0));

        ÜrünTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ürün İsmi", "Kategori", "Fiyat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ÜrünTablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ÜrünTablosuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ÜrünTablosu);

        Ürün_ekle.setText("Ürün Ekle");
        Ürün_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ürün_ekleActionPerformed(evt);
            }
        });

        ürün_güncelleme.setText("Ürün Güncelle");
        ürün_güncelleme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ürün_güncellemeActionPerformed(evt);
            }
        });

        sil_butonu.setText("Ürün Sil");
        sil_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sil_butonuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MesajYazısı, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_ürün_ismi)
                                    .addComponent(tf_fiyat)
                                    .addComponent(CBKategori, 0, 130, Short.MAX_VALUE))))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ürün_güncelleme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Ürün_ekle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sil_butonu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_ürün_ismi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ürün_ekle))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CBKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ürün_güncelleme))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_fiyat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sil_butonu))
                .addGap(18, 18, 18)
                .addComponent(MesajYazısı, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Ürün_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ürün_ekleActionPerformed
        MesajYazısı.setText(" ");
        DefaultTableModel model = (DefaultTableModel)ÜrünTablosu.getModel();
        if(tf_ürün_ismi.getText().trim().equals("")) {
            MesajYazısı.setText("Ürün ismi boş bırakılamaz.");
        }
        else {
            Object[] eklenecek = {tf_ürün_ismi.getText(),CBKategori.getSelectedItem(),tf_fiyat.getText()};
            model.addRow(eklenecek);
        }
    }//GEN-LAST:event_Ürün_ekleActionPerformed

    private void ürün_güncellemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ürün_güncellemeActionPerformed
        MesajYazısı.setText("");
        DefaultTableModel model = (DefaultTableModel)ÜrünTablosu.getModel();
        int secili_row = ÜrünTablosu.getSelectedRow();
        if(secili_row == -1){
            if(ÜrünTablosu.getRowCount() == 0) {
                MesajYazısı.setText("Ürün tablosu şu an boş");
            }
            else {
                MesajYazısı.setText("Lütfen güncellenecek bir ürün seçin.");
            }
        }
        else {
            model.setValueAt(tf_ürün_ismi.getText(), secili_row, 0);
            model.setValueAt(CBKategori.getSelectedItem(), secili_row, 1);
            model.setValueAt(tf_fiyat.getText(), secili_row, 2);
            MesajYazısı.setText("Ürün başarıyla güncellendi.");
        }
    }//GEN-LAST:event_ürün_güncellemeActionPerformed

    private void ÜrünTablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ÜrünTablosuMouseClicked
        DefaultTableModel model = (DefaultTableModel) ÜrünTablosu.getModel();
        
        int secili_row = ÜrünTablosu.getSelectedRow();
        tf_ürün_ismi.setText(model.getValueAt(secili_row, 0).toString());
        CBKategori.setSelectedItem(model.getValueAt(secili_row, 1).toString());
        tf_fiyat.setText(model.getValueAt(secili_row, 2).toString());

    }//GEN-LAST:event_ÜrünTablosuMouseClicked

    private void sil_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sil_butonuActionPerformed
        DefaultTableModel model = (DefaultTableModel) ÜrünTablosu.getModel();
        
        int secili_row = ÜrünTablosu.getSelectedRow();
        if(secili_row == -1) {
            if(ÜrünTablosu.getRowCount() == 0) {
                MesajYazısı.setText("Ürün tablosu şu an boş");
            }
            else {
                MesajYazısı.setText("Lütfen güncellenecek bir ürün seçin.");
            }
        }
        else {
            model.removeRow(secili_row);
            MesajYazısı.setText("Ürün başarıyla silindi.");
        }
    }//GEN-LAST:event_sil_butonuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StokUygulaması.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StokUygulaması.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StokUygulaması.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StokUygulaması.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StokUygulaması().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBKategori;
    private javax.swing.JLabel MesajYazısı;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton sil_butonu;
    private javax.swing.JTextField tf_fiyat;
    private javax.swing.JTextField tf_ürün_ismi;
    private javax.swing.JTable ÜrünTablosu;
    private javax.swing.JButton Ürün_ekle;
    private javax.swing.JButton ürün_güncelleme;
    // End of variables declaration//GEN-END:variables
}
